$("#dailyMinTemp0").html(dzien[0].temperatureMin);
$("#dailyMinTemp1").html(dzien[1].temperatureMin);
$("#dailyMinTemp2").html(dzien[2].temperatureMin);
$("#dailyMinTemp3").html(dzien[3].temperatureMin);
$("#dailyMinTemp4").html(dzien[4].temperatureMin);
$("#dailyMinTemp5").html(dzien[5].temperatureMin);
$("#dailyMinTemp6").html(dzien[6].temperatureMin);
$("#dailyMinTemp7").html(dzien[7].temperatureMin);

$("#dailyMaXTemp0").html(dzien[0].temperatureMaX);
$("#dailyMaXTemp1").html(dzien[1].temperatureMaX);
$("#dailyMaXTemp2").html(dzien[2].temperatureMaX);
$("#dailyMaXTemp3").html(dzien[3].temperatureMaX);
$("#dailyMaXTemp4").html(dzien[4].temperatureMaX);
$("#dailyMaXTemp5").html(dzien[5].temperatureMaX);
$("#dailyMaXTemp6").html(dzien[6].temperatureMaX);
$("#dailyMaXTemp7").html(dzien[7].temperatureMaX*100);
var d1=new Date(parseInt(dzien[0].time.substr(6)));
$("#dailyTime0").html(d1);
$("#dailyTime1").html(dzien[1].time);
$("#dailyTime2").html(dzien[2].time);
$("#dailyTime3").html(dzien[3].time);
$("#dailyTime4").html(dzien[4].time);
$("#dailyTime5").html(dzien[5].time);
$("#dailyTime6").html(dzien[6].time);
$("#dailyTime7").html(dzien[7].time);
